# Generated by Django 3.1.2 on 2020-12-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_auto_20201209_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
