# Generated by Django 3.1.2 on 2020-12-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
